//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDesk.Localization.Views.PushNotificationSettings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketDesk.Localization.Views.PushNotificationSettings.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti-noise settings.
        /// </summary>
        public static string AntiNoise_Header {
            get {
                return ResourceManager.GetString("AntiNoise_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Ticket Notifications.
        /// </summary>
        public static string BroadcastNotification_Header {
            get {
                return ResourceManager.GetString("BroadcastNotification_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery providers.
        /// </summary>
        public static string Delivery_Header {
            get {
                return ResourceManager.GetString("Delivery_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TicketDesk is running demo mode. Push notifications are disabled.&lt;/p&gt;
        ///                            &lt;p&gt; To turn off demo mode, please change the setting in application configuration.&lt;/p&gt;.
        /// </summary>
        public static string DemoMode_Alert {
            get {
                return ResourceManager.GetString("DemoMode_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General settings.
        /// </summary>
        public static string General_Header {
            get {
                return ResourceManager.GetString("General_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push notification settings.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one provider must be enabled in order for messages to be sent..
        /// </summary>
        public static string RequiredProvider {
            get {
                return ResourceManager.GetString("RequiredProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved!.
        /// </summary>
        public static string Saved_Alert {
            get {
                return ResourceManager.GetString("Saved_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveOption {
            get {
                return ResourceManager.GetString("SaveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Root Url.
        /// </summary>
        public static string SiteRootUrl {
            get {
                return ResourceManager.GetString("SiteRootUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting is vital to ensure that hyperlinks in emails contain the currect URL to your site..
        /// </summary>
        public static string SiteRootUrl_Help {
            get {
                return ResourceManager.GetString("SiteRootUrl_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url is invalid. If you are trying to use localhost for testing, specify the loopback IP address instead (http://127.0.0.1:80).
        /// </summary>
        public static string SiteRootUrl_Validation {
            get {
                return ResourceManager.GetString("SiteRootUrl_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Notification Settings.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use current root URL.
        /// </summary>
        public static string UseCurrentURL {
            get {
                return ResourceManager.GetString("UseCurrentURL", resourceCulture);
            }
        }
    }
}
