// <auto-generated />
namespace TicketDesk.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Td25011 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Td25011));
        
        string IMigrationMetadata.Id
        {
            get { return "201504020337366_Td2.5.011"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
