//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDesk.Domain.Model.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppModelText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppModelText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketDesk.Domain.Model.Localization.AppModelText", typeof(AppModelText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affects Customer.
        /// </summary>
        public static string TicketAffectsCustomer {
            get {
                return ResourceManager.GetString("TicketAffectsCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned To.
        /// </summary>
        public static string TicketAssignedTo {
            get {
                return ResourceManager.GetString("TicketAssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string TicketCategory {
            get {
                return ResourceManager.GetString("TicketCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string TicketCreatedBy {
            get {
                return ResourceManager.GetString("TicketCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on __date__ by __user__.
        /// </summary>
        public static string TicketCreatedCombined {
            get {
                return ResourceManager.GetString("TicketCreatedCombined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string TicketCreatedDate {
            get {
                return ResourceManager.GetString("TicketCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status.
        /// </summary>
        public static string TicketCurrentStatus {
            get {
                return ResourceManager.GetString("TicketCurrentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status By.
        /// </summary>
        public static string TicketCurrentStatusBy {
            get {
                return ResourceManager.GetString("TicketCurrentStatusBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status Date.
        /// </summary>
        public static string TicketCurrentStatusDate {
            get {
                return ResourceManager.GetString("TicketCurrentStatusDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string TicketDetails {
            get {
                return ResourceManager.GetString("TicketDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Html.
        /// </summary>
        public static string TicketIsHtml {
            get {
                return ResourceManager.GetString("TicketIsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated By.
        /// </summary>
        public static string TicketLastUpdateBy {
            get {
                return ResourceManager.GetString("TicketLastUpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated Date.
        /// </summary>
        public static string TicketLastUpdateDate {
            get {
                return ResourceManager.GetString("TicketLastUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated on __date__ by __user__.
        /// </summary>
        public static string TicketLastUpdatedCombined {
            get {
                return ResourceManager.GetString("TicketLastUpdatedCombined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string TicketOwner {
            get {
                return ResourceManager.GetString("TicketOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string TicketPriority {
            get {
                return ResourceManager.GetString("TicketPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status on __date__ by __user__.
        /// </summary>
        public static string TicketStatusCombined {
            get {
                return ResourceManager.GetString("TicketStatusCombined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TicketTagList {
            get {
                return ResourceManager.GetString("TicketTagList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket #.
        /// </summary>
        public static string TicketTicketId {
            get {
                return ResourceManager.GetString("TicketTicketId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TicketTicketType {
            get {
                return ResourceManager.GetString("TicketTicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TicketTitle {
            get {
                return ResourceManager.GetString("TicketTitle", resourceCulture);
            }
        }
    }
}
