// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace TicketDesk.Web.Client.Areas.Admin.Controllers {
    public partial class SecurityManagementController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SecurityManagementController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult UsersList() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.UsersList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult EditUser() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.EditUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult DeleteUser() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.DeleteUser);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SecurityManagementController Actions { get { return MVC.Admin.SecurityManagement; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "SecurityManagement";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string UsersList = "UsersList";
            public readonly string EditUser = "EditUser";
            public readonly string CreateUser = "CreateUser";
            public readonly string DeleteUser = "DeleteUser";
            public readonly string RolesList = "RolesList";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string CreateUser = "~/Areas/Admin/Views/SecurityManagement/CreateUser.aspx";
            public readonly string DeleteUser = "~/Areas/Admin/Views/SecurityManagement/DeleteUser.aspx";
            public readonly string EditUser = "~/Areas/Admin/Views/SecurityManagement/EditUser.aspx";
            public readonly string Index = "~/Areas/Admin/Views/SecurityManagement/Index.aspx";
            public readonly string UsersList = "~/Areas/Admin/Views/SecurityManagement/UsersList.aspx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_SecurityManagementController: TicketDesk.Web.Client.Areas.Admin.Controllers.SecurityManagementController {
        public T4MVC_SecurityManagementController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UsersList(int page) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.UsersList);
            callInfo.RouteValueDictionary.Add("page", page);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditUser(string userName) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EditUser);
            callInfo.RouteValueDictionary.Add("userName", userName);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditUser(TicketDesk.Web.Client.Areas.Admin.Models.SecurityManagementUserViewModel user) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EditUser);
            callInfo.RouteValueDictionary.Add("user", user);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CreateUser() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CreateUser);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CreateUser(TicketDesk.Web.Client.Areas.Admin.Models.SecurityManagementUserViewModel user) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CreateUser);
            callInfo.RouteValueDictionary.Add("user", user);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DeleteUser(string userName) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DeleteUser);
            callInfo.RouteValueDictionary.Add("userName", userName);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DeleteUser(TicketDesk.Web.Client.Areas.Admin.Models.SecurityManagementUserViewModel user) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DeleteUser);
            callInfo.RouteValueDictionary.Add("user", user);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult RolesList() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.RolesList);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
