// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace TicketDesk.Web.Client.Areas.Admin.Controllers {
    public partial class EmailTemplateController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected EmailTemplateController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult DisplayHtml() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.DisplayHtml);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult DisplayOutlookHtml() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.DisplayOutlookHtml);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult DisplayText() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.DisplayText);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public EmailTemplateController Actions { get { return MVC.Admin.EmailTemplate; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "EmailTemplate";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string ProcessWaitingNotesNow = "ProcessWaitingNotesNow";
            public readonly string DisplayHtml = "DisplayHtml";
            public readonly string DisplayOutlookHtml = "DisplayOutlookHtml";
            public readonly string DisplayText = "DisplayText";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Index = "~/Areas/Admin/Views/EmailTemplate/Index.aspx";
            public readonly string TicketNotificationHtmlEmailTemplate = "~/Areas/Admin/Views/EmailTemplate/TicketNotificationHtmlEmailTemplate.ascx";
            public readonly string TicketNotificationOutlookHtmlEmailTemplate = "~/Areas/Admin/Views/EmailTemplate/TicketNotificationOutlookHtmlEmailTemplate.ascx";
            public readonly string TicketNotificationTextEmailTemplate = "~/Areas/Admin/Views/EmailTemplate/TicketNotificationTextEmailTemplate.ascx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_EmailTemplateController: TicketDesk.Web.Client.Areas.Admin.Controllers.EmailTemplateController {
        public T4MVC_EmailTemplateController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index(int? id, string mode) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            callInfo.RouteValueDictionary.Add("id", id);
            callInfo.RouteValueDictionary.Add("mode", mode);
            return callInfo;
        }

        public override System.Web.Mvc.ContentResult ProcessWaitingNotesNow() {
            var callInfo = new T4MVC_ContentResult(Area, Name, ActionNames.ProcessWaitingNotesNow);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DisplayHtml(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DisplayHtml);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DisplayOutlookHtml(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DisplayOutlookHtml);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DisplayText(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DisplayText);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
