// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace TicketDesk.Web.Client.Controllers {
    public partial class TicketCenterController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected TicketCenterController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult List() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.List);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult FilterList() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.FilterList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SortList() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SortList);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TicketCenterController Actions { get { return MVC.TicketCenter; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "TicketCenter";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string List = "List";
            public readonly string FilterList = "FilterList";
            public readonly string SortList = "SortList";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string TicketCenter = "~/Views/TicketCenter/TicketCenter.aspx";
            static readonly _Controls s_Controls = new _Controls();
            public _Controls Controls { get { return s_Controls; } }
            public partial class _Controls{
                public readonly string FilterBar = "~/Views/TicketCenter/Controls/FilterBar.ascx";
                public readonly string ListViewMenu = "~/Views/TicketCenter/Controls/ListViewMenu.ascx";
                public readonly string TicketList = "~/Views/TicketCenter/Controls/TicketList.ascx";
                public readonly string TicketListItem = "~/Views/TicketCenter/Controls/TicketListItem.ascx";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_TicketCenterController: TicketDesk.Web.Client.Controllers.TicketCenterController {
        public T4MVC_TicketCenterController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult List(int? page, string listName) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.List);
            callInfo.RouteValueDictionary.Add("page", page);
            callInfo.RouteValueDictionary.Add("listName", listName);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult FilterList(string listName, int pageSize, string currentStatus, string owner, string assignedTo) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.FilterList);
            callInfo.RouteValueDictionary.Add("listName", listName);
            callInfo.RouteValueDictionary.Add("pageSize", pageSize);
            callInfo.RouteValueDictionary.Add("currentStatus", currentStatus);
            callInfo.RouteValueDictionary.Add("owner", owner);
            callInfo.RouteValueDictionary.Add("assignedTo", assignedTo);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SortList(string listName, string columnName, bool isMultiSort) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SortList);
            callInfo.RouteValueDictionary.Add("listName", listName);
            callInfo.RouteValueDictionary.Add("columnName", columnName);
            callInfo.RouteValueDictionary.Add("isMultiSort", isMultiSort);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
