//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDesk.Localization.Views.TicketActivity {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketDesk.Localization.Views.TicketActivity.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affects Customer.
        /// </summary>
        public static string AffectsCustomer_Label {
            get {
                return ResourceManager.GetString("AffectsCustomer_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TicketDesk is running demo mode. Attachment Uploads are disabled.&lt;/p&gt;
        ///                            &lt;p&gt; To turn off demo mode, please change the setting in application configuration.&lt;/p&gt;.
        /// </summary>
        public static string Attachment_Demo_Alert {
            get {
                return ResourceManager.GetString("Attachment_Demo_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop attachments here, or click to select files..
        /// </summary>
        public static string Attachment_Instructions {
            get {
                return ResourceManager.GetString("Attachment_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Attachments_Label {
            get {
                return ResourceManager.GetString("Attachments_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Comment_EditOption {
            get {
                return ResourceManager.GetString("Comment_EditOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment_Label {
            get {
                return ResourceManager.GetString("Comment_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Comment_PreviewOption {
            get {
                return ResourceManager.GetString("Comment_PreviewOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Details_EditOption {
            get {
                return ResourceManager.GetString("Details_EditOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details_Label {
            get {
                return ResourceManager.GetString("Details_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Details_PreviewOption {
            get {
                return ResourceManager.GetString("Details_PreviewOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Form_CancelOption {
            get {
                return ResourceManager.GetString("Form_CancelOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket title.
        /// </summary>
        public static string Form_TicketTitle_Placeholder {
            get {
                return ResourceManager.GetString("Form_TicketTitle_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign to me?.
        /// </summary>
        public static string ReOpen_AssignToMe {
            get {
                return ResourceManager.GetString("ReOpen_AssignToMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this box to assign the ticket to yourself now. If unchecked the ticket will be re-opened as unassigned..
        /// </summary>
        public static string ReOpen_Instructions {
            get {
                return ResourceManager.GetString("ReOpen_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ReOpen_Label {
            get {
                return ResourceManager.GetString("ReOpen_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck this to supply information without changing the ticket&apos;s status..
        /// </summary>
        public static string SupplyMoreInfo_Instructions {
            get {
                return ResourceManager.GetString("SupplyMoreInfo_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SupplyMoreInfo_Label {
            get {
                return ResourceManager.GetString("SupplyMoreInfo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactivate Ticket.
        /// </summary>
        public static string SupplyMoreInfo_ReactivateTicket {
            get {
                return ResourceManager.GetString("SupplyMoreInfo_ReactivateTicket", resourceCulture);
            }
        }
    }
}
