//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TicketDesk.Domain.Models.DataAnnotations
{
    public partial class SettingMeta
    {
    		
    	[DisplayName("Setting Name")]
    	[Required]
    	[StringLength(50)]
        public string SettingName { get; set; }
    		
    	[DisplayName("Setting Value")]
    	[Required]
        public string SettingValue { get; set; }
    }
}
