// <auto-generated />
namespace TicketDesk.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-beta1-20501")]
    public sealed partial class TD0300001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TD0300001));
        
        string IMigrationMetadata.Id
        {
            get { return "201308070506527_TD03.0.0.001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
