// <auto-generated />
namespace TicketDesk.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Td25003 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Td25003));
        
        string IMigrationMetadata.Id
        {
            get { return "201412302236209_Td2.5.003"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
