//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDesk.Web.Models.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppUIText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppUIText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketDesk.Web.Models.Localization.AppUIText", typeof(AppUIText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TicketDesk 3.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to navbar-brand title.
        /// </summary>
        internal static string CssNavLogo {
            get {
                return ResourceManager.GetString("CssNavLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string GeneralBack {
            get {
                return ResourceManager.GetString("GeneralBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string GeneralCancel {
            get {
                return ResourceManager.GetString("GeneralCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string GeneralNo {
            get {
                return ResourceManager.GetString("GeneralNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string GeneralRefresh {
            get {
                return ResourceManager.GetString("GeneralRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string GeneralSave {
            get {
                return ResourceManager.GetString("GeneralSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string GeneralYes {
            get {
                return ResourceManager.GetString("GeneralYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string NavAccountLogin {
            get {
                return ResourceManager.GetString("NavAccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string NavAccountLogout {
            get {
                return ResourceManager.GetString("NavAccountLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string NavAccountMenuAdministration {
            get {
                return ResourceManager.GetString("NavAccountMenuAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Panel.
        /// </summary>
        internal static string NavAccountMenuAdminPanel {
            get {
                return ResourceManager.GetString("NavAccountMenuAdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your account.
        /// </summary>
        internal static string NavAccountMenuManageUser {
            get {
                return ResourceManager.GetString("NavAccountMenuManageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string NavAccountMenuOptions {
            get {
                return ResourceManager.GetString("NavAccountMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string NavMainAdmin {
            get {
                return ResourceManager.GetString("NavMainAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string NavMainHome {
            get {
                return ResourceManager.GetString("NavMainHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Ticket.
        /// </summary>
        internal static string NavMainTicketCreate {
            get {
                return ResourceManager.GetString("NavMainTicketCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Details.
        /// </summary>
        internal static string NavMainTicketDetails {
            get {
                return ResourceManager.GetString("NavMainTicketDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Center.
        /// </summary>
        internal static string NavMainTickets {
            get {
                return ResourceManager.GetString("NavMainTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle navigation.
        /// </summary>
        internal static string NavMainToggleNavigation {
            get {
                return ResourceManager.GetString("NavMainToggleNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate away and cancel your changes?.
        /// </summary>
        internal static string NavNavigateAwayConfirmDialogMessage {
            get {
                return ResourceManager.GetString("NavNavigateAwayConfirmDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to leave __pagetitle__?.
        /// </summary>
        internal static string NavNavigateAwayConfirmDialogTitle {
            get {
                return ResourceManager.GetString("NavNavigateAwayConfirmDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string PagerNext {
            get {
                return ResourceManager.GetString("PagerNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to found.
        /// </summary>
        internal static string PagerNumberFound {
            get {
                return ResourceManager.GetString("PagerNumberFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string PagerOf {
            get {
                return ResourceManager.GetString("PagerOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string PagerPage {
            get {
                return ResourceManager.GetString("PagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string PagerPrevious {
            get {
                return ResourceManager.GetString("PagerPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to records.
        /// </summary>
        internal static string PagerTotalTickets {
            get {
                return ResourceManager.GetString("PagerTotalTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms-PL license - ©2013 Stephen M. Redd.
        /// </summary>
        internal static string ViewFooterCopyright {
            get {
                return ResourceManager.GetString("ViewFooterCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login as user &apos;admin&apos; with a password of &apos;admin&apos; or user &apos;otherstaffer&apos; with a password of &apos;otherstaffer&apos;.&lt;br /&gt;&lt;br /&gt;This deployment is based off of a private branch where I&apos;m working out the security framework. Currently, this is backed by the new Asp.Net Identity Framework. I am in the process of migrating to the DurandalAuth UI template.&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;Translations for the login fetures are incomplete at this time, but for the rest of the spanish example translations &lt;a href=&apos;/?setLng=es&apos;&gt;click here&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewHomeContent {
            get {
                return ResourceManager.GetString("ViewHomeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TicketDesk Home.
        /// </summary>
        internal static string ViewHomeTitle {
            get {
                return ResourceManager.GetString("ViewHomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed!.
        /// </summary>
        internal static string ViewLoginFailedErrorMessage {
            get {
                return ResourceManager.GetString("ViewLoginFailedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string ViewLoginLoginButtonLabel {
            get {
                return ResourceManager.GetString("ViewLoginLoginButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ViewLoginPasswordFieldLabel {
            get {
                return ResourceManager.GetString("ViewLoginPasswordFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string ViewLoginRememberMeFieldLabel {
            get {
                return ResourceManager.GetString("ViewLoginRememberMeFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string ViewLoginTitle {
            get {
                return ResourceManager.GetString("ViewLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string ViewLoginUserNameFieldLabel {
            get {
                return ResourceManager.GetString("ViewLoginUserNameFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string ViewLogoutTitle {
            get {
                return ResourceManager.GetString("ViewLogoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Ticket.
        /// </summary>
        internal static string ViewTicketCreateTitle {
            get {
                return ResourceManager.GetString("ViewTicketCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Details.
        /// </summary>
        internal static string ViewTicketDetailsTitle {
            get {
                return ResourceManager.GetString("ViewTicketDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tickets.
        /// </summary>
        internal static string ViewTicketListTitle {
            get {
                return ResourceManager.GetString("ViewTicketListTitle", resourceCulture);
            }
        }
    }
}
