//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDesk.Localization.Views.UserAdministration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Edit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Edit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketDesk.Localization.Views.UserAdministration.Edit", typeof(Edit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrators.
        /// </summary>
        public static string Administrators {
            get {
                return ResourceManager.GetString("Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users who will manage TicketDesk&apos;s settings, and can manage user accounts and permissions. This role also includes all permissions from Help Desk Staff and Internal User roles..
        /// </summary>
        public static string Administrators_Description {
            get {
                return ResourceManager.GetString("Administrators_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to users.
        /// </summary>
        public static string BackOption {
            get {
                return ResourceManager.GetString("BackOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelOption {
            get {
                return ResourceManager.GetString("CancelOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseOption {
            get {
                return ResourceManager.GetString("CloseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be undone..
        /// </summary>
        public static string DeleteAlert {
            get {
                return ResourceManager.GetString("DeleteAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this account?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteOption {
            get {
                return ResourceManager.GetString("DeleteOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Details.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Desk Staff.
        /// </summary>
        public static string HelpDeskStaff {
            get {
                return ResourceManager.GetString("HelpDeskStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privledged users to whom tickets will be assigned. This role has access to the full set of ticket activities. This role also includes all permissions of the Intnerl User role..
        /// </summary>
        public static string HelpDeskStaff_Description {
            get {
                return ResourceManager.GetString("HelpDeskStaff_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Users.
        /// </summary>
        public static string InternalUsers {
            get {
                return ResourceManager.GetString("InternalUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role is for end-users. They can submit tickets, can be set as a ticket&apos;s owner, and can perform a limited set of operations against owned tickets..
        /// </summary>
        public static string InternalUsers_Description {
            get {
                return ResourceManager.GetString("InternalUsers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage user account.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Approval.
        /// </summary>
        public static string PendingApproval {
            get {
                return ResourceManager.GetString("PendingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unless configured differently in application settings, this is the default role users are assigned during registration. This role has no privledges within TicketDesk. It is intended as a marker to help administrators quickly locate new accounts before promoting them to a different role..
        /// </summary>
        public static string PendingApproval_Description {
            get {
                return ResourceManager.GetString("PendingApproval_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveOption {
            get {
                return ResourceManager.GetString("SaveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show role descriptions.
        /// </summary>
        public static string ShowRoleDescriptions {
            get {
                return ResourceManager.GetString("ShowRoleDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User Account.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
