//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TicketDesk.Domain.Models.DataAnnotations
{
    public partial class AdCachedUserPropertyMeta
    {
    		
    	[DisplayName("User Name")]
    	[Required]
    	[StringLength(150)]
        public string UserName { get; set; }
    		
    	[DisplayName("Property Name")]
    	[Required]
    	[StringLength(100)]
        public string PropertyName { get; set; }
    		
    	[DisplayName("Property Value")]
    	[StringLength(250)]
        public string PropertyValue { get; set; }
    		
    	[DisplayName("Last Refreshed")]
        public Nullable<System.DateTime> LastRefreshed { get; set; }
    		
    	[DisplayName("Is Active In Ad")]
    	[Required]
        public bool IsActiveInAd { get; set; }
    }
}
