//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TicketDesk.Domain.Models.DataAnnotations
{
    public partial class TicketTagMeta
    {
    		
    	[DisplayName("Ticket Tag Id")]
    	[Required]
        public int TicketTagId { get; set; }
    		
    	[DisplayName("Tag Name")]
    	[Required]
    	[StringLength(100)]
        public string TagName { get; set; }
    		
    	[DisplayName("Ticket Id")]
    	[Required]
        public int TicketId { get; set; }
    }
}
